import type { Metadata } from "next";
import { Header, Footer } from '@/components';
import { Inter } from 'next/font/google';

import "./globals.css";

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

const interFont = Inter({
    subsets: ['latin'],
    weight: "600",
    variable: "--font-inter"
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${interFont.variable}`}>
      <body>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
